FROM python:3.10-slim

WORKDIR /app

COPY requirements_services.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY sending_retail.py

RUN mkdir -p /app/results /app/logs

RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

ENTRYPOINT ["python", "sending_retail.py"]